<?php

/**
 * Implements hook_library_info_build().
 */
function alternative_editors_library_info_build() {
  $libraries = [];

  foreach (['ckeditor', 'tinymce'] as $editor) {
    $libraries[$editor] = [
      'js' => [
        'js/' . $editor . '.js' => [],
      ],
      'dependencies' => [
        'editor/drupal.editor',
      ],
    ];
    $config = \Drupal::config('alternative_editors.settings');
    $selfHosted = $config->get($editor . '_self_hosted');
    $jsPath = $config->get( $editor . '_javascript_path');
    $libraries[$editor]['js'][$jsPath] = $selfHosted
      ? ['minified' => TRUE]
      : ['minified' => TRUE, 'external' => TRUE];
  }

  return $libraries;
}
