tinymce.settings:
  type: config_object
  label: 'Alternative editors settings'
  mapping:
    tinymce_javascript_path:
      type: string
      label: 'tinymce.min.js full path'
    tinymce_self_hosted:
      type: boolean
      label: 'Self hosted'
